#!/usr/bin/env python3
"""Convert the design-system icon sprite (assets/icons.svg) into a WPF
ResourceDictionary of DrawingImages (src/Retro.Wpf/Themes/Icons.xaml).

Usage: python3 tools/svg2xaml.py design/assets/icons.svg src/Retro.Wpf/Themes/Icons.xaml
"""
import re
import sys
import xml.etree.ElementTree as ET

SVG = "{http://www.w3.org/2000/svg}"

# The exported sprite references these classes without shipping their styles;
# colors are chosen from the design tokens (colors_and_type.css).
PALETTE = {
    "doc-line": "#000000",
    "doc-fill": "#FFFFFF",
    "doc-fold": "#A6B4C5",
    "white": "#FFFFFF",
    "blue": "#2A6FB8",
    "blue-d": "#003D7A",
    "gray": "#8A95A5",
    "green": "#2E8B3E",
    "red": "#C8281E",
    "yellow": "#F0AB00",
}

# Pixel-drawn replacement for the <text>?</text> glyph in the "help" icon.
HELP_GLYPH = [(5, 3, 6, 2), (9, 5, 2, 2), (5, 5, 2, 1), (7, 7, 2, 2), (7, 10, 2, 2)]


def pascal(name):
    special = {"saveas": "SaveAs", "x": "Close"}
    if name in special:
        return special[name]
    return "".join(p.capitalize() for p in name.split("-"))


def fmt(v):
    f = float(v)
    return str(int(f)) if f.is_integer() else repr(round(f, 3))


def fill_of(el):
    if el.get("fill") is not None:
        f = el.get("fill")
        return None if f == "none" else f
    cls = el.get("class")
    if cls:
        return PALETTE[cls]
    return "#000000"


def pen_of(el):
    s = el.get("stroke")
    if not s or s == "none":
        return None
    return s, fmt(el.get("stroke-width", "1"))


def geometry(el):
    tag = el.tag.replace(SVG, "")
    if tag == "rect":
        return "<RectangleGeometry Rect=\"{},{},{},{}\"/>".format(
            fmt(el.get("x", 0)), fmt(el.get("y", 0)), fmt(el.get("width")), fmt(el.get("height")))
    if tag == "circle":
        r = fmt(el.get("r"))
        return "<EllipseGeometry Center=\"{},{}\" RadiusX=\"{}\" RadiusY=\"{}\"/>".format(
            fmt(el.get("cx")), fmt(el.get("cy")), r, r)
    if tag == "line":
        return "<LineGeometry StartPoint=\"{},{}\" EndPoint=\"{},{}\"/>".format(
            fmt(el.get("x1")), fmt(el.get("y1")), fmt(el.get("x2")), fmt(el.get("y2")))
    if tag == "polygon":
        pts = el.get("points").split()
        return "<StreamGeometry>M{} L{} Z</StreamGeometry>".format(pts[0], " ".join(pts[1:]))
    if tag == "path":
        d = re.sub(r"\s+", " ", el.get("d").strip())
        return "<StreamGeometry>{}</StreamGeometry>".format(d)
    raise ValueError("unsupported element " + tag)


def drawing(el, indent):
    pad = " " * indent
    brush = fill_of(el)
    pen = pen_of(el)
    tag = el.tag.replace(SVG, "")
    if tag == "line":
        brush = None
    attrs = ' Brush="{}"'.format(brush) if brush else ""
    out = [pad + "<GeometryDrawing{}>".format(attrs)]
    if pen:
        out.append(pad + '  <GeometryDrawing.Pen><Pen Brush="{}" Thickness="{}"/></GeometryDrawing.Pen>'.format(*pen))
    out.append(pad + "  <GeometryDrawing.Geometry>" + geometry(el) + "</GeometryDrawing.Geometry>")
    out.append(pad + "</GeometryDrawing>")
    return out


def transform_of(g):
    t = g.get("transform", "")
    if t.replace(" ", "") == "translate(16,0)scale(-1,1)":
        return "-1,0,0,1,16,0"
    if t:
        raise ValueError("unsupported transform " + t)
    return None


def children(sym, symbols, indent):
    out = []
    pad = " " * indent
    for el in sym:
        tag = el.tag.replace(SVG, "")
        if tag == "use":
            ref = el.get("href").lstrip("#")
            out.extend(children(symbols[ref], symbols, indent))
        elif tag == "g":
            m = transform_of(el)
            out.append(pad + "<DrawingGroup{}>".format(' Transform="{}"'.format(m) if m else ""))
            out.extend(children(el, symbols, indent + 2))
            out.append(pad + "</DrawingGroup>")
        elif tag == "text":
            for (x, y, w, h) in HELP_GLYPH:
                out.append(pad + '<GeometryDrawing Brush="#FFFFFF" Geometry="M{0},{1} h{2} v{3} h-{2} Z"/>'.format(x, y, w, h))
        else:
            out.extend(drawing(el, indent))
    return out


def main(src, dst):
    root = ET.parse(src).getroot()
    symbols = {s.get("id"): s for s in root.iter(SVG + "symbol")}
    lines = [
        "<!-- Generated by tools/svg2xaml.py from the design-system icon sprite. Do not edit by hand. -->",
        '<ResourceDictionary xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"',
        '                    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"',
        '                    xmlns:po="http://schemas.microsoft.com/winfx/2006/xaml/presentation/options">',
    ]
    for sid, sym in symbols.items():
        lines.append('  <DrawingImage x:Key="Retro.Icon.{}" po:Freeze="True">'.format(pascal(sid)))
        lines.append("    <DrawingImage.Drawing>")
        lines.append('      <DrawingGroup ClipGeometry="M0,0 H16 V16 H0 Z">')
        lines.append('        <GeometryDrawing Brush="Transparent" Geometry="M0,0 H16 V16 H0 Z"/>')
        lines.extend(children(sym, symbols, 8))
        lines.append("      </DrawingGroup>")
        lines.append("    </DrawingImage.Drawing>")
        lines.append("  </DrawingImage>")
    lines.append("</ResourceDictionary>")
    with open(dst, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print("\n".join(pascal(s) for s in symbols))


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
